Receive:
  Email:
    - "2078170660@qq.com"

Send:
  - Email : "2078170660@qq.com"
    SMTPPwd : "vgddliqnapbbdcji"
    SMTPServer : "smtp.qq.com:465"

Template:
  MessageTmp : "æ˜¯{}çš„ç”Ÿæ—¥ğŸ‚ï¼Œå…·ä½“æ—¥æœŸæ˜¯{}ï¼ˆ{}ï¼‰"
  HaveAgeMessageTmp : "æ˜¯{}çš„{}å²ç”Ÿæ—¥ğŸ‚ï¼Œå…·ä½“æ—¥æœŸæ˜¯{}ï¼ˆ{}ï¼‰"
